import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html >
  );
}
/* agrego el authContext para que los perfiles autenticados peudan renderizar datos de forma dinamica como nombres categorias y demas, sin necesidad de duplicar codigo en los distintos sidebar o perfiles. 

Evita duplicar llamadas: Si el usuario pasa del dashboard de jugador al dashboard del club (o a una vista pública), el estado del usuario ya está cargado en memoria y no tiene que volver a pedir el auth/me.

Acceso global: Te permite usar useAuth() tanto en el sidebar de Player, en la navegación de Club, como en la barra superior pública para mostrar, por ejemplo, el botón de "Ir a mi panel" o el nombre de quien inició sesión.*/